### ISSUE TITLE
zkvm: boolean `not` instruction

### ISSUE THREAD

**Issue by oleganza** [interstellar/slingshot#117]
There's a cool trick to implement logical negation described in [Setty, Vu, Panpalia, Braun, Ali, Blumberg, Walfish (2012)](https://eprint.iacr.org/2012/598.pdf) (appendix D.1), later [implemented in libsnark](https://github.com/scipr-lab/libsnark/blob/dfa74ff270ca295619be1fdf7661f76dff0ae69e/libsnark/gadgetlib1/gadgets/basic_gadgets.hpp#L162-L169). It lets us use just two multipliers:

```
x - the input secret scalar mod |G|.
y - the output of NOT(x): if x == 0 then 1 else 0.
w - additional free variable chosen by the prover.
```

Statements in R1CS:

```
x·y = 0
x·w = 1-y
```

* The first statement implies that `y == 0` when `x != 0`.
* The second statement implies that `y == 1` when `x == 0`. 
* To satisfy both statements, the prover must choose `w` to be `x^-1 mod |G|` if `x != 0`.
* If `x == 0` the `w` could be set to an arbitrary value.

### Spec draft

Stack diagram for the `not` instruction:

_constr1_ **not** → _constr2_

1. Allocate two multipliers.
2. Constrain the first mult's left wire to the input constraint (`x`).
3. Constrain the second mult's left wire to first mult's left wire (i.e. `x == x` on both multipliers).
4. Assign the second mult's right wire (`w`) to the inverse of input constraint `x` or zero if it's zero. No constraints needed for `w`.
5. Constrain the first mult's output wire to `0`.
6. Constrain the second mult's output wire to `1-y`, where `y` is the first mult's right wire.
7. Wrap the first mult's right wire (`y`) in a Constraint `constr2` and push it to the stack.

![image](https://user-images.githubusercontent.com/698/54410687-be70ed80-46a9-11e9-97b5-1e66fe14c2ee.png)

(4 constraints)

### Implementation notes

1. Add `Constraint::Not(Box<Constraint>)` variant to existing `::Eq/Or/And`.
2. Note that truth is represented by equations `stuff == 0`, therefore, the truth of NOT is represented by `y == 0` (which means that the corresponding input to the NOT must satisfy `stuff ≠ 0`).

### Alternative

@cathieyun made a good point that if we simply need to check that something is not zero, we could use a _single multiplier_ using statement `x·w == 1`, where `w` must be chosen to be `x^-1 mod |G|`. 

This could be used with a hypothetical instruction `notverify` that inverses the composition of boolean functions (And/Or). Unfortunately, this does not permit nice compositions like `not(x) and y`, `not(x) or y`. Bringing `not` outside in these would bring back `not` to the other term.

2-multiplier `not` instruction seems to be of a minor overhead and is easily composable with the rest of boolean operations, so probably the tradeoff is worth it.

**Comment by ebfull** [comment]
Note that you can also enforce that N different values are nonzero using only a single auxillary inversion by multiplying them all together. (HT @daira also on that one.)
