### ISSUE TITLE
zkvm: guaranteed optimization for constant constraints

### ISSUE THREAD

**Issue by oleganza** [interstellar/slingshot#252]
Like we cannot soft-fork more efficient arithmetic on non-secret expressions (aka "numbers"), we cannot do the same for constraints (aka "booleans"). So maybe it makes sense to have a clean "guaranteed optimization" for constant constraints too (that are created by doing `eq` on two constant expressions):

- [x] Change `eq` to create new variant `Constraint::Cleartext(bool)` if both arguments are _constant expressions_. Boolean is `true` if they are equal, `false` otherwise.
- [x] Change `and` in case one of the constraints is `Cleartext`: return the other argument as-is if it's true, or return `Cleartext(false)` if it's false.
- [x] Change `or` in case one of the constraints is `Cleartext`: return the other argument as-is if it's false, or return `Cleartext(true)` if it's true.
- [x] Change `not` for `Cleartext` argument: invert the boolean.
- [x] Change `verify` for `Cleartext` argument: fail execution if it's `false`, and simply drop the argument if it's `true`.

When flattening non-cleartext constraint, the `Cleartext()` case is guaranteed to not show up, as it's always optimized away, but compiler still requires matching on all enum variants. To make it clean, convert `true` to const-expression of `0` (not a typo), and `false` to const-expression of `1`. Plus, add a comment, that this is never supposed to be executed.

**Comment by cathieyun** [comment]
(copied from pr #287):

What is the reasoning for having a cleartext constraint type in addition to a non-secret expression type? If I understand correctly, we could just represent the cleartext constraint type ("boolean") as a non-secret expression ("number") and have the same behavior?
