### ISSUE TITLE
ZkVM: Spec Questions

### ISSUE THREAD

**Issue by decentralisedkev** [interstellar/slingshot#71]
https://github.com/interstellar/slingshot/blob/main/zkvm/spec/ZkVM.md#aggregated-signature

"Commit all verification keys P[i] in order, one by one"

Would this be in lexographical order?

Can the terms clear-text scalars and non-secret scalars be used interchangeably?

The term "Flavour" was defined in the Cloak protocol, should we copy over the definition for the specs?

**Comment by oleganza** [comment]
>"Commit all verification keys P[i] in order, one by one"

In the order they are provided. Since they come from `signtx` instructions, the order corresponds to the order of use of these instructions.

**Comment by oleganza** [comment]
>Can the terms clear-text scalars and non-secret scalars be used interchangeably?

Yup. Probably need to fix up the spec to use "clear-text" across the board for clarity and to avoid this ambiguity.

**Comment by oleganza** [comment]
>The term "Flavour" was defined in the Cloak protocol, should we copy over the definition for the specs?

We can probably simply link to the Cloak spec from the terms _quantity_ and _flavor_ in the `Value` definition.

**Comment by oleganza** [comment]
I'll leave this issue open until i tweak the spec to address these points.
