### ISSUE TITLE
zkvm end-to-end unit tests

### ISSUE THREAD

**Issue by oleganza** [interstellar/slingshot#78]
As we are approaching complete Prover/Verifier set of APIs (cf. #72), here are the unit tests that we want to make for the low-level API (#61):

1. Issue $10 (with nonce) into a pubkey.
2. Spend two utxos with $6+$4 into $9 and $1 outputs.
3. Spend 2 utxos into 1 output.
4. Spend 1 utxo into 2 outputs.
5. Spend 1 utxo into 1 output.
6. Issue (w/o nonce) $4 while spending $6 from a utxo into $9 and $1.
7. Have variants of these tests for inconsistent amounts - these should fail at verification.

**Comment by cathieyun** [comment]
PR for tests 2-7 here: https://github.com/interstellar/slingshot/pull/100

**Comment by cathieyun** [comment]
https://github.com/interstellar/slingshot/pull/100 merged, closing this issue!
