### ISSUE TITLE
ZkVM: inconsistent terminology around Expressions/Variables

### ISSUE THREAD

**Issue by oleganza** [interstellar/slingshot#82]
@decentralisedkev pointed this out in a private conversation:

>Neg instruction states that:
>
>>2.If the expression is a *detached* variable, attaches it to the constraint system.
>
>Does this conflict with the part in Attached and Detached Variables, which states:
>
>>When an expression is formed using detached variables, all of them transition to an attached state?
>
>If it does then, I may need to edit the part on Expressions which states that:
>
>>Expression is a linear combination of attached variables with cleartext scalar weights.?

Sources: [`neg`](https://github.com/interstellar/slingshot/blob/main/zkvm/spec/ZkVM.md#neg), [Attached and detached variables](https://github.com/interstellar/slingshot/blob/main/zkvm/spec/ZkVM.md#attached-and-detached-variables), [Expression](https://github.com/interstellar/slingshot/blob/main/zkvm/spec/ZkVM.md#expression-type).

The short answer is: "Expression" is accidentally used both as an object representing a linear combination of low-level and high-level variables, as well as a "supertype" of a Variable (since any variable can be turned into a linear combination of itself at no cost), which allows using variables where expressions are expected w/o explicit conversion.

How do we make this more clear?

### Option 1: explicit name for the supertype

Rewrite all the parts of the spec where `Expression | Variable` is expected in terms of this supertype, and reflect this in implementation with explicit conversion to expression with attaching the vars as necessary.

### Option 2: explicit conversion instruction for Variable->Expression

Instruction `attach` (or `expr`) would turn the `Variable` into `Expression` and attach it into R1CS. The spec can be made simpler, and the user is more explicitly aware of the variable being attached. But we expose this extra instruction which seems like a bit of redundancy. But maybe things would be overall more clear and less footgunny.

PR: #84 

### Else

Other ideas?

**Comment by oleganza** [comment]
Will try to make a PR for "Option 2".

**Comment by decentralisedkev** [comment]
If I understand correctly, any variable can be coerced into an expression, but an expression with multiple linear combinations cannot be coerced into a variable. Option1 would add a new name for the supertype Expression-Variable, while option2 adds an instruction.

I was leaning towards option2 more because it is more explicit... new type or new instruction

**Comment by oleganza** [comment]
With you we now have 4 people leaning towards option 2 and no one against.
