### ISSUE TITLE
token: abstraction for issuing and retiring tokens

### ISSUE THREAD

**Issue by oleganza** [interstellar/slingshot#95]
This is related issue to **Accounts API** #94:

Features:

1. Create a token
2. Issue a token
3. Compute amount of outstanding tokens in circulation
4. Receive and retire tokens
5. Embed and verify metadata into the token's flavor.

See #94 for more considerations w.r.t. statefulness and FFI.

**Comment by oleganza** [comment]
A few thoughts after reading through #139:

### API focus

Maybe the proper name for this API is not "Treasury", but "Token"?

1. You can define token with a given predicate.
2. You can issue token as a one-shot tx (issue-and-send-to), or as a partial program in a larger transaction.
3. Embed/verify metadata in a token.
4. Issue/retire protocol loop with abstracted storage.

### Flexibility

If we let the user provide the predicate, we can separate the concerns: they would be able to construct a multi-sig/multi-party configurations w/o the API making these decisions for them.

Then, we can have separate tooling for fancy predicates that could be used with both issuers and accounts.

### Program separation

Issuance is probably going to be one of the actions in a transaction. Even if we start with a "one shot" function that "issues to an address", it's still better to separate two-three layers, at least internally:

1. Issuing a value to a stack.
2. Transferring the value to a destination.
3. Composing the whole transaction (and adding `nonce` if there are no inputs).

### Signing separation

For all operations with tokens but signing an issuance, we should not require `PredicateWitness::Key`. So we need to allow creating a `Token` type with a more opaque predicate (maybe still a witness tree, but w/o signing keys, if we need to know the structure), but when composing a program for signing, be able to provide the keys separately. Maybe we'll need to redesign `PredicateWitness::Key` entirely to use an indirect reference to signing material — that may be needed to accommodate both in-HSM signing and multi-party signing.

### Circulation

Circulation seems to be out of scope, but the accurate way to compute it is by processing proved-to-be-published transactions, not just incrementing a counter in a table we one signed off. 

So we'll need a generic trait for the "state" part of the following "state machine":

1. When issuing: store the `qty_commitment -> (qty,blinding)` pair for later retrieval.
2. When retiring: store the `qty_commitment -> (qty,blinding)` and `flv_commitment -> (flv,blinding)` pairs for later retrieval.
3. When detecting an issuance of a Token's flavor (flavor is unblinded): load `qty_commitment -> (qty,blinding)` pair and attempt to verify qty. Store increased circulation. If the quantity is unknown, store the reference to this issuance as "unknown".
4. When detecting a retirement, look up `flv_commitment -> (flv,blinding)` that corresponds to the token in question. If it does, look up `qty_commitment -> (qty,blinding)` to decrement qty. If `qty` is not found for the given commitment, store an unknown retirement. Note: this should probably never happen as if someone else is blinding qty away from the issuer/auditor, they'd blind the flavor too.

Note: the goal of this protocol is _not to help issuer enforce_ some specific way of things being issued or retired (that's the goal of the logic within the predicate), but solely to correctly index the transactions performed by the issuer themselves and avoid miscalculations due to doubly-signed/re-signed or never co-signed/published transactions.

**Comment by vickiniu** [comment]
In the event that we have the `Token`/`Treasury` API just return programs that can be composed into a tx, would circulation be purely managed from watching the blockchain state?

**Comment by oleganza** [comment]
>In the event that we have the `Token`/`Treasury` API just return programs that can be composed into a tx, would circulation be purely managed from watching the blockchain state?

Not sure i understood the question, but it seems to me that those are unrelated. No matter how we construct transactions, we can only be sure in the circulation numbers _after_ ingesting actually published transactions.
